tokenizer:
  model_name: gpt2
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True 

reward_fn:
    id: meteor
    args: {}

datapool:
  id: commongen
  args:
    concept_end_token: '.'
    concept_separator_token: ';'

env:
  n_envs: 10
  args:
    max_prompt_length: 5
    max_episode_length: 24
    terminate_on_eos: True

alg:
  id: ppo
  args: 
    n_steps: 128
    batch_size: 32
    verbose: 1
    learning_rate: 0.000005
    n_epochs: 10
    ent_coef: 0.0001
  kl_div:
    coeff: 0.01
    batch_size: 64
  policy:
    args:
      model_name: gpt2
      apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        max_new_tokens: 24  #this must align with env's max steps
  
train_evaluation:
  eval_batch_size: 256
  n_iters: 200
  eval_every: 20
  metrics:
    - id: meteor
      args: {}
    - id: rouge
      args:
        rouge_type: "rouge1"
    - id: rouge
      args:
        rouge_type: "rouge2"
    - id: rouge
      args:
        rouge_type: "rougeL"
    - id: bert_score
      args:
        language: "en"
    - id: bleu
      args: {}
    - id: bleurt
      args: {}
    - id: diversity
      args: {}

