tokenizer:
  model_name: gpt2
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True

reward_fn:
  id: increasing_numbers
  args:
    min_tokens: 20

datapool:
  id: dummy_pool
  args:
    n_samples: 50
    prompt: '<|endoftext|>'

env:
  n_envs: 1
  args:
    max_prompt_length: 5
    max_episode_length: 20
    terminate_on_eos: False

policy:
  args:
    model_name: gpt2
    apply_model_parallel: True

alg:
  id: trpo
  args:
    n_steps: 8
    batch_size: 4
    verbose: 1
    learning_rate: 0.00001
  kl_div:
    coeff: 0.01
    batch_size: 4

train_evaluation:
  eval_batch_size: 32
  n_iters: 100
  eval_every: 5
  metrics:
    - id: increasing_numbers
      args:
        min_tokens: 20
  generation_kwargs:
    do_sample: True
    min_length: 20
    max_new_tokens: 20

