tokenizer:
  model_name: gpt2
  padding_side: right
  truncation_side: right
  pad_token_as_eos_token: True

reward_fn:
  id: increasing_numbers
  args:
    min_tokens: 20

datapool:
  id: dummy_pool
  args:
    n_samples: 50
    prompt: 'Lets generate increasing numbers'
env:
  n_envs: 10
  args:
    max_prompt_length: 5
    max_episode_length: 20
    terminate_on_eos: True
    context_start_token: 0

alg:
  id: oldt
  args:
    n_steps: 128
    batch_size: 8
    verbose: 1
    learning_rate: 0.00001
    n_epochs: 1
    train_freq: 1
    gradient_steps: 50
  kl_div:
    coeff: 0.001
    batch_size: 64
  policy:
    id: causal_lm_actor_only_policy
    args:
      model_name: gpt2
      apply_model_parallel: True
      weight_decay: 0.001
      generation_kwargs:
        do_sample: True
        top_k: 0
        min_length: 20
        max_new_tokens: 20  # this must align with env's max steps

train_evaluation:
  eval_batch_size: 256
  n_iters: 200
  eval_every: 10
  save_every: 10
  control_token: '[1.0]'
  metrics:
    - id: increasing_numbers
      args:
          min_tokens: 20