tokenizer:
  model_name: t5-base
  padding_side: right
  truncation_side: right
  pad_token_as_eos_token: True 

reward_fn:
  id: learned_reward
  args: 
    model_name: lvwerra/distilbert-imdb
    label_ix: 1

datapool:
  id: imdb
  args: {}

env:
  n_envs: 10
  args:
    max_prompt_length: 64
    max_episode_length: 48
    terminate_on_eos: True
    context_start_token: 0

alg:
  id: ppo
  args: 
    n_steps: 128
    batch_size: 64
    verbose: 1
    learning_rate: 0.000001
    n_epochs: 5
    ent_coef: 0.001
  kl_div:
    coeff: 0.1
    batch_size: 64
  policy:
    id: seq2seq_lm_policy
    args:
      model_name: t5-base
      apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        max_new_tokens: 48
        min_length: 48
      
train_evaluation:
  eval_batch_size: 256
  n_iters: 100
  eval_every: 5
  metrics:
    - id: learned_reward
      args: 
        model_name: lvwerra/distilbert-imdb
        label_ix: 1
        batch_size: 100