tokenizer:
  model_name: gpt2
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True 

reward_fn:
  id: meteor
  args: {}

datapool:
  id: totto
  args: {}

env:
  n_envs: 5
  args:
    max_prompt_length: 128
    max_episode_length: 48
    terminate_on_eos: False

alg:
  id: ppo
  args: 
    n_steps: 128
    batch_size: 32
    verbose: 1
    learning_rate: 0.00001
    n_epochs: 5
    ent_coef: 0.001
  kl_div:
    coeff: 0.1
    batch_size: 64
  policy:
    args:
      model_name: gpt2
      apply_model_parallel: True
  
train_evaluation:
  eval_batch_size: 256
  n_iters: 100
  eval_every: 20
  metrics:
    - id: meteor
      args: {}
    - id: rouge
      args:
        rouge_type: "rouge1"
    - id: rouge
      args:
        rouge_type: "rouge2"
    - id: rouge
      args:
        rouge_type: "rougeL"
    - id: bleu
      args: {}
    - id: bleurt
      args: {}
    - id: diversity
      args: {}
    
  generation_kwargs:
    do_sample: True
    min_length: 272 # max prompt length + min tokens ??
    max_new_tokens: 48