tokenizer:
  model_name: gpt2
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True

reward_fn:
  expand: True
  values:
    - id: meteor

datapool:
  id: crd3
  args:
    max_context_size: 5

env:
  n_envs: 10
  args:
    max_prompt_length: 256
    max_episode_length: 20
    terminate_on_eos: True

alg:
  id: ppo
  args: 
    n_steps: 256
    batch_size: 64
    verbose: 1
    learning_rate:
      expand: True
      values: [0.000005, 0.00001]
    ent_coef: 0.0
  kl_div:
    coeff: 0.01
    target_kl: 4.0
  policy:
    id: causal_lm_actor_critic_policy
    args:
      model_name: gpt2
      apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        top_k: 50
        max_new_tokens: 20
  
train_evaluation:
  eval_batch_size: 100
  n_iters: 100
  eval_every: 25
  save_every: 1
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: sacre_bleu
    - id: bert_score
      args:
        language: "en"
    - id: diversity
      args: {}
  generation_kwargs:
    do_sample: True
    top_k: 50
    max_new_tokens: 20

