tokenizer:
  model_name: lvwerra/gpt2-imdb
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True

reward_fn:
  id: learned_reward
  args:
    model_name: lvwerra/distilbert-imdb
    label_ix: 1

datapool:
  id: imdb
  args: {}

env:
  n_envs: 8
  args:
    max_prompt_length: 64
    max_episode_length: 48
    terminate_on_eos: True

alg:
  id: nlpo
  args:
    n_steps: 128
    batch_size: 32
    verbose: 1
    learning_rate:
      expand: True
      values: [0.0000001]
    n_epochs: 5
  kl_div:
    coeff: 0.001
    batch_size: 32
  policy:
    id: maskable_causal_lm_actor_critic_policy
    args:
      model_name: lvwerra/gpt2-imdb
      apply_model_parallel: True
      top_mask:
        expand: True
        values: [ 1000, 10000 ]
      mask_type:
        expand: True
        values: [ 'learned', 'topk' ]
      generation_kwargs:
        do_sample: True
        top_k: 0
        min_length: 32
        max_new_tokens: 128

train_evaluation:
  eval_batch_size: 32
  n_iters: 200
  eval_every: 10
  metrics:
    - id: learned_reward
      args:
        model_name: lvwerra/distilbert-imdb
        label_ix: 1
        batch_size: 100