tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: meteor

datapool:
  id: cnn_daily_mail
  args:
    prompt_prefix: "summarize: "

env:
  n_envs: 8
  args:
    max_prompt_length: 512
    max_episode_length: 128
    terminate_on_eos: True
    prompt_truncation_side: "right"
    context_start_token: 0

alg:
  id: nlpo
  args:
    n_steps: 256
    batch_size: 32
    verbose: 1
    learning_rate: 0.000001
    n_epochs: 5
    ent_coef: 0.0
  kl_div:
    coeff: 0.01
    target_kl: 0.2
  policy:
    id: maskable_seq2seq_lm_actor_critic_policy
    args:
      model_name: t5-base
      apply_model_parallel: True
      prompt_truncation_side: "right"
      top_mask: 0.7
      mask_type: 'learned_top_p'
      target_update_iterations: 10
      generation_kwargs:
        do_sample: True
        min_length: 32
        max_new_tokens: 128

train_evaluation:
  eval_batch_size: 64
  n_iters: 200
  eval_every: 20
  metrics:
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    # - id: bleurt
    #   args:
    #     config_name: bleurt-large-512
    - id: diversity
      args: {}
