tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False 

reward_fn:
  id: learned_reward
  args: 
    model_name: lvwerra/distilbert-imdb
    label_ix: 1
    include_prompt_for_eval: True

datapool:
  id: imdb
  args: {}

env:
  n_envs: 10
  args:
    max_prompt_length: 128
    max_episode_length: 48
    terminate_on_eos: True
    context_start_token: 0

alg:
  id: ppo
  args: 
    n_steps:
      expand: True 
      values: [128]
    batch_size: 64
    verbose: 1
    learning_rate: 
      expand: True 
      values: [0.00001, 0.000001]
    n_epochs: 5
    ent_coef: 0.0
  kl_div:
    coeff: 0.1
    target_kl: 0.2

  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: t5-base
      apply_model_parallel: True
      generation_kwargs:
        do_sample: True
        max_new_tokens: 48
        min_length: 48
      
train_evaluation:
  eval_batch_size: 256
  n_iters: 100
  eval_every: 10
  metrics:
    - id: learned_reward
      args: 
        model_name: lvwerra/distilbert-imdb
        label_ix: 1
        batch_size: 100