tokenizer:
  model_name: facebook/blenderbot-400M-distill
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False


datapool:
  id: "daily_dialog"
  args:
    context_size: 5

alg:
  id: supervised
  training_args:
    per_device_train_batch_size: 16
    logging_steps: 5000
    num_train_epochs: 10
    weight_decay: 0.1
    lr_scheduler_type: cosine
    learning_rate: 0.0001
    save_total_limit: 1
  model_type: seq2seq
  model_name: facebook/blenderbot-400M-distill
  generation_kwargs:
    min_length: 5
    max_new_tokens: 20  # this must align with env's max steps
    num_beams: 4
    post_processing_fn: null

train_evaluation:
  eval_batch_size: 32
  metrics:
    - id: intent_accuracy
    - id: diversity
      args: {}
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: sacre_bleu
      args:
        tokenize: "intl"

