tokenizer:
  model_name: microsoft/DialoGPT-medium
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: True
  max_length: 128

datapool:
  id: "daily_dialog"
  args:
    context_size: 5

alg:
  id: supervised
  training_args:
    per_device_train_batch_size:
      expand: True
      values: [32]
    logging_steps: 300
    num_train_epochs:
      expand: True
      values: [20]
    lr_scheduler_type: "constant"
    learning_rate: 
      expand: True 
      values: [0.00001]
    save_total_limit: 1
  model_type: causal
  model_name: microsoft/DialoGPT-medium
  generation_kwargs:
    expand: True
    values:
      - do_sample: True
        top_k: 20
        min_length: 2
        max_new_tokens: 20
        post_processing_fn: null

train_evaluation:
  eval_batch_size: 256
  metrics:
    - id: intent_accuracy
    - id: causal_perplexity
      args:
        tokenizer_id: microsoft/DialoGPT-medium
        stride: 128
        model_type: causal
    - id: diversity
      args: {}
    - id: meteor
      args: {}
    - id: rouge
    - id: bleu
      args: {}
    - id: bert_score
      args:
        language: en
    - id: sacre_bleu
      args:
        tokenize: "intl"

